config/routes.rb
Rails.application.routes.draw do

 root 'blogs#index'
 get 'show' => 'blogs#show'
 get 'contact' => 'static_pages#contact'
 get 'blogs/:id/edit', to: 'blogs#edit', as: :edit_blog
 
devise_for :users 
devise_scope :user do 
	get '/users/sign_out' => 'devise/sessions#destroy'
end

 resources :blogs, only: [:index, :create, :update, :destroy, :edit]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)


    if user.try(:admin?)
        can :manage, :all 
    else

        can :update, Blog do |blog|
            blog.user == user
        end

        can :destroy, Blog do |blog|
            blog.user == user
        end

        can :create, Blog

        end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 140}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :blogs


  def admin? 
  	self.admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController


  def index 	
  	@blogs = Blog.paginate(page: params[:page], :per_page => 9, :total_entries =>9)
  end

  def show
	@blogs = Blog.paginate(page: params[:page], :per_page => 9)
  end


  def new
    @blog = current_user.blogs.build
  end


  def create 
    if current_user
      @blog = current_user.blogs.build(blog_params)     
      @blog.save
      redirect_to root_url
    else  
      flash[:alert] = "Будь ласка, увійдіть щоб мати можливість додавати свої пости"
      redirect_to root_url
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    if @blog.present?
    @blog.destroy
    redirect_to root_path
  end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update 
    @blog = Blog.find(params[:id])
    @blog.update(content: params[:blog][:content])
    redirect_to root_path
  end


  private
  def blog_params
    params.require(:blog).permit(:content)
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blogs/_blog.html.erb
<ul id="blog-<%= blog.id %>" class = "blogs">
	<li> 
	<span class="user" ><%= blog.user.email %></span> 
 	<span class="content"><%= blog.content %></span> 
  	<span  class="timestamp">Posted <%= time_ago_in_words(blog.created_at) %> ago.</span> 
  	<% if can? :update, blog %>
  	<%= link_to "Edit", edit_blog_path(blog.id) %>
  	<% end %>
  	<% if can? :destroy, blog %>
  	<%= link_to "Destroy", blog_path(blog.id), :method => :delete %>
  	<% end %>
  	</li>
</ul>

app/views/blogs/edit.html.erb
<%= form_for (@blog) do |f| %>

	<%= f.label "Введіть текст" %>
	<%= f.text_field :content, class: 'form-control' %>

	<%= f.submit "Зберегти", class: 'btn btn-primary'%>

<% end %>

app/views/blogs/index.html.erb
<!--Carousel element -->
<%= render 'layouts/carousel' %>
<ol class="blogs">
	<%= render @blogs %>
</ol>
<%= will_paginate @blogs %>


<%= form_for(Blog.new) do |f| %>


<div class="field">
<%= f.text_area :content, placeholder: "Напишіть новий блог" %>
</div>
<%= f.submit "Додати", class: "btn btn-primary" %>
<% end %>

app/views/blogs/show.html.erb
<ol class="blogs">
	<%= render @blogs %>
</ol>
<%= will_paginate @blogs %>

app/views/layouts/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">

        <div class="carousel-item active">
            <img class="d-block w-100" src="https://placeimg.com/1080/500/animals" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
                <h5>Welcome to my site!</h5>
                <p>Here you can write your own blogs</p>
            </div>
        </div>

        <div class="carousel-item">
            <img class="d-block w-100" src="https://placeimg.com/1080/500/arch" alt="Second slide">
        </div>

        <div class="carousel-item">
            <img class="d-block w-100" src="https://placeimg.com/1080/500/nature" alt="Third slide">
        </div>

    </div>

    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>

    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

app/views/layouts/_header.html.erb
<header>
	<nav class = "navbar navbar-expand-md navbar-dark bg-dark">
		<div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
			<ul class="navbar-nav mr-auto">
				<li class="nav-link"><%= link_to "Головна", root_path %></li>
				<li class="nav-link"><%= link_to "Блог", show_path %></li>
				<li class="nav-link"><%= link_to "Контакти", contact_path %></li>
				
			</ul>
		</div>
		<div class="navbar navbar-expand-md navbar-dark bg-dark">
			<ul class="navbar-nav mx-auto">
				<% if current_user%> 
			  <li class="nav-link">	Ласкаво просимо, <%=current_user.email.split('@')[0].capitalize%> </li> 
			  	<% else %> 
			  	<% end %>
			</ul>
		</div>

		<div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
			<ul class="navbar-nav ml-auto">				
				<li class="nav-link"><%= link_to "Увійти", new_user_session_path %></li>
				<li class="nav-link"><%= link_to "Зареєструватись", new_user_registration_path %></li>
				<li class="nav-link"><%= link_to "Вийти", destroy_user_session_path%></li>
			</ul>
		</div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :after_js %>
  </head>

  <body>


    <!-- Header element -->
    <%= render 'layouts/header'%>

      <% flash.each do |type, msg| %>
          <div class="alert alert-info">
          <%= msg %>
          </div>
      <% end %>
      
    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>Andrii Stegnytskyi, Ruby on Rails developer</h1>
<p>Telephone nr. : +48538200421</p>
<p>Email: a.stegnytskyi@gmail.com</p>